title: <p align="center"> Yashraj Pathak </p>
logo: assets/img/WhatsApp Image 2021-11-02 at 9.52.41 PM.png

description:
  <p align="center">
  <a href="https://drive.google.com/file/d/1QLMhcVmDpAJOGHtjyxdvktOSI8ROaGVi/view?usp=sharing">Resume</a> |
  <a href="https://www.linkedin.com/in/yashraj-pathak">LinkedIn</a> |
  <a href="https://github.com/YashrajPathak">GitHub</a>
  
  <br>   
  ML Practitioner | Data Analyst | IIIT-B | Liverpool John Moores University | Data Scientist | Python | Actively Looking for Deep Learning/ ML Engineer role  
  <br>
  </p>
