title: <p align="center"> Yashraj Pathak </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://drive.google.com/file/d/1QLMhcVmDpAJOGHtjyxdvktOSI8ROaGVi/view?usp=sharing">Resume</a> |
  <a href="https://www.linkedin.com/in/yashraj-pathak">LinkedIn</a> |
  <a href="https://github.com/YashrajPathak">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
